"""returner transport tables

Revision ID: 46615d932d32
Revises: a1eb3a459e7d
Create Date: 2026-09-10 11:37:07.784521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46615d932d32'
down_revision: Union[str, None] = 'a1eb3a459e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jids',
    sa.Column('jid', sa.String(length=255), nullable=False),
    sa.Column('load', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('jid')
    )
    op.create_table('salt_returns',
    sa.Column('fun', sa.String(length=50), nullable=False),
    sa.Column('jid', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('return', sa.JSON(), nullable=False),
    sa.Column('full_ret', sa.JSON(), nullable=False),
    sa.Column('alter_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('jid', 'id')
    )
    op.create_index('idx_salt_returns_fun', 'salt_returns', ['fun'], unique=False)
    op.create_index('idx_salt_returns_id', 'salt_returns', ['id'], unique=False)
    op.create_index('idx_salt_returns_jid', 'salt_returns', ['jid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_salt_returns_jid', table_name='salt_returns')
    op.drop_index('idx_salt_returns_id', table_name='salt_returns')
    op.drop_index('idx_salt_returns_fun', table_name='salt_returns')
    op.drop_table('salt_returns')
    op.drop_table('jids')
    # ### end Alembic commands ###
