"""salt_events transport table

Revision ID: 95ffc8849775
Revises: 46615d932d32
Create Date: 2026-09-10 11:54:02.385610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95ffc8849775'
down_revision: Union[str, None] = '46615d932d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salt_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('alter_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('master_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_salt_events_tag', 'salt_events', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_salt_events_tag', table_name='salt_events')
    op.drop_table('salt_events')
    # ### end Alembic commands ###
