"""baseline

Revision ID: a1eb3a459e7d
Revises: 
Create Date: 2026-09-10 10:39:40.669113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1eb3a459e7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('jid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created', 'audit_events', ['created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('jid', sa.String(length=32), nullable=False),
    sa.Column('fun', sa.String(length=128), nullable=False),
    sa.Column('tgt', sa.Text(), nullable=False),
    sa.Column('tgt_type', sa.String(length=16), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('jid')
    )
    op.create_table('minions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('key_status', sa.String(length=16), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grains', sa.JSON(), nullable=False),
    sa.Column('conformity', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('fun', sa.String(length=128), nullable=False),
    sa.Column('tgt', sa.Text(), nullable=False),
    sa.Column('tgt_type', sa.String(length=16), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('watched_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sls', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sls')
    )
    op.create_table('job_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jid', sa.String(length=32), nullable=False),
    sa.Column('minion_id', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('retcode', sa.Integer(), nullable=False),
    sa.Column('return', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['jid'], ['jobs.jid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_returns_jid', 'job_returns', ['jid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_returns_jid', table_name='job_returns')
    op.drop_table('job_returns')
    op.drop_table('watched_states')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('saved_jobs')
    op.drop_table('minions')
    op.drop_table('jobs')
    op.drop_index('ix_audit_events_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
